name: pr-build

on:
  pull_request:
  merge_group:

jobs:
  pr-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install and Run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

      - name: Find globals
        uses: LiangYuxuan/action-findglobals@v2
        with:
          find-args: "! -path \"./Libs/*\""

      - name: Create Retail Package
        uses: BigWigsMods/packager@v2
        with:
          args: "-d -z"

      - uses: actions/upload-artifact@v5
        with:
          name: pull-request-${{ github.event.number }}-${{ github.sha }}
          path: .release/
