name: update-license

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 1 1 *

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Update license year
        uses: p3lim/license-year-updater@v2
        with:
          files: LICENSE

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update license
          commit-message: "chore: update license"
          branch: update-license
          delete-branch: true
